Ext.application({
		name: 'SP',
		requires : ['SP.GlobalConfig'],
		appFolder : 'app',
	    extend: 'Ext.app.Application',
		autoCreateViewport : true,
		controllers : ['Customer' , 
		               'CustomerType' , 
		               'CustomerLevel', 
		               'SystemMenu',
		               'ChannelType',
		               'ChannelLevel',
		               'BusinessMode',
		               'Region',
		               'Market',
		               'Business',
		               'Material' , 
				       'DistributePlan',
		               'DistributePlanConfig'],
		               
		models : ['CustomerModel',
		          'CustomerType',
		          'CustomerLevel',
		          'ChannelType',
		          'ChannelLevel',
		          'BusinessMode',
		          'Region',
		          'Market',
		          'Business',
		          'Material',
		          'DistributePlanItem'],
		          
		stores : ['Customer' , 
		          'SystemMenu', 
		          'CustomerType' , 
		          'CustomerLevel', 
		          'ChannelType', 
		          'ChannelLevel',
		          'BusinessMode',
		          'Region',
		          'Market',
		          'Business',
		          'Material',
		          'DistributePlanItem',
		          'DistributePlanDraft',
		          'DistributePlanUnpublish',
		          'DistributePlanInProcess',
		          'DistributePlanFinished'
		          ]
});